name: Run Daily IT Job Screener
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 14 * * *' 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Libraries
        run: pip install requests groq beautifulsoup4
      - name: Run Screener Engine
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python screener.py
        
      - name: Check if CSV or Status message exists
        id: check_files
        run: |
          if [ -f "today_jobs.csv" ]; then
            echo "mail_body=Hi Edwin, attached is your automated morning IT job spreadsheet match list!" >> $GITHUB_ENV
            echo "mail_attach=today_jobs.csv" >> $GITHUB_ENV
          else
            echo "mail_body=$(cat status.txt)" >> $GITHUB_ENV
            echo "mail_attach=" >> $GITHUB_ENV
          fi

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ://gmail.com
          server_port: 465
          username: ${{ secrets.MY_EMAIL }}
          password: ${{ secrets.MY_PASSWORD }}
          subject: 🎯 Daily IT Job Screener Update
          to: ${{ secrets.TARGET_EMAIL }}
          from: Daily IT Job Screener
          body: ${{ env.mail_body }}
          attachments: ${{ env.mail_attach }}
